schema: "classroom50/repo-config/v1"
classroom: "cis-3515-fall-2026"
assignment: "class-activity-4"
owner:
  username: "dylanlanza"
  id: 228963667
  accepted_at: "2026-09-10T15:19:46Z"
source:
  owner: "karlmorris"
  owner_id: 1034071
  repo: "CIS3515_Activity_4"
  branch: "master"
